version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - './data/spark/scripts:/opt/bitnami/spark/scripts'
      - './data/spark/datasets:/opt/bitnami/spark/datasets'
      - './data/spark/init-env.sh:/docker-entrypoint-initdb.d/init-env.sh'
      - './requirements.txt:/docker-entrypoint-initdb.d/requirements.txt'
      - './.env:/opt/bitnami/spark/scripts/.env'


  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - './data/spark/init-env.sh:/docker-entrypoint-initdb.d/init-env.sh'
      - './requirements.txt:/docker-entrypoint-initdb.d/requirements.txt'

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=project

  clickhouse:
    image: docker.io/bitnami/clickhouse:24
    environment:
      - CLICKHOUSE_ADMIN_USER=admin
      - CLICKHOUSE_ADMIN_PASSWORD=password
    ports:
      - '8123:8123'
    volumes:
      - 'clickhouse:/bitnami/clickhouse'
      - './data/clickhouse:/docker-entrypoint-initdb.d' # chmod +x init-db.sh


volumes:
  clickhouse:
  minio: